### ISSUE TITLE
Database update scripts

### ISSUE THREAD

**Issue by DustinDEV2more** [RecieSage/API#9]
Ich denke in der Zukunft wird sich die Datenbank vielemale ändern. Daher sollte ein "System" erstellt werden, welches die Datenbank aufsetzt und danach immer Datenbank update scripts aussührt wenn diese noch nicht aufgeführt wurden. Welche Scripts bereits ausgeführt wurden, sollte in der Datenbank selbst getrackt werden.

Die API soll beim starten schauen, ob die Datenbank zu der sie verbunden wird eine Tabelle hat, welche Trackt welche Update Scripts ausgeführt wurden. Wenn nicht soll sie das "create database" script einspielen und alle datenbank scripts in richter reinfolge hinterherr. Diese sollen dann in die Tabelle eingetragen werden

Wenn die Tabelle exisitert dann sollen alle scripts in der richtigen reinfolge ausgeführt werden, dessen ausführung noch nicht in der Tabelle bestätigt wurden.

**Comment by DustinDEV2more** [comment]
# Todo:

- [ ] Create_Database Script
- [ ] Database Check at startup logic
- [ ] Database Update checks
- [ ] Upadte Database logic

**Comment by DustinDEV2more** [comment]
Erkenntnisse:
- Datenbank scripts selber schreiben > generierte scripts
- In den scripts nicht definieren welche Datenbank verwendet werden soll. Das muss das Programm regeln. Nicht das script
